### ISSUE TITLE
Unable to do `udacity submit` due to absence of the `.udacity-pa` folder in the repo

### ISSUE THREAD

**Issue by abhi18av** [udacity/AIND-Recognizer#21]
Hi **udacity-team** 

I was trying to submit my solution for review regarding this final project of `Term-1` but I wasn't able to do so.  It would fail with the following error message 

```sh
aind-recognizer git/master  9s
(aind) ❯ udacity submit
Traceback (most recent call last):
  File "/Users/eklavya/anaconda/envs/aind/bin/udacity", line 7, in <module>
    from udacity_pa.projectassistant import main_func
  File "/Users/eklavya/anaconda/envs/aind/lib/python3.6/site-packages/udacity_pa/projectassistant.py", line 29, in <module>
    raise  NotProjectAssistantError()
udacity_pa.projectassistant.NotProjectAssistantError: Not an Udacity Project Assistant directory. No .udacity-pa folder found.

```

After a little digging, I found that the presence of `.udacity-pa` is necessary for a proper authentication and clearly this was what's lacking from this repo since all other `Term-1` repos do have their own respective `.udacity-pa/projects.py` file.

https://github.com/udacity/AIND-Sudoku/blob/master/.udacity-pa/projects.py

https://github.com/udacity/AIND-Isolation/blob/master/.udacity-pa/projects.py

https://github.com/udacity/AIND-Planning/blob/master/.udacity-pa/projects.py

But it's not in this repo. Could you please fix this soon ?

**Comment by cgearhart** [comment]
This project is not scored by the Project Assistant. You simply submit the required files as a zip archive through the classroom.

**Comment by abhi18av** [comment]
Oh, I see!

Thanks :)

**Comment by la3lma** [comment]
I have the same  problem, and my project _is_ scored by project assistant, but alas no upload via the  the assistant script seems possible.
