### ISSUE TITLE
ModelSelector vs SelectorModel

### ISSUE THREAD

**Issue by jamesrequa** [udacity/AIND-Recognizer#7]
The ModelSelector class is being referred to as the SelectorModel class in the asl_recognizer notebook. Below is how it is currently written in the notebook for reference. 

"Review the **SelectorModel** class from the codebase found in the my_model_selectors.py module. It is designed to be a strategy pattern for choosing different model selectors. For the project submission in this section, subclass **SelectorModel** to implement the following model selectors."

**Comment by danainschool** [comment]
closing - looks like this was fixed
